{% set name = "python-ulid" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_ulid-{{ version }}.tar.gz
  sha256: e50296a47dc8209d28629a22fc81ca26c00982c78934bd7766377ba37ea49a9f

build:
  entry_points:
    - ulid = ulid.__main__:entrypoint
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ulid
  commands:
    - pip check
    - ulid --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Universally unique lexicographically sortable identifier
  home: https://github.com/mdomke/python-ulid
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
