{% set name = "python-ulid" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_ulid-{{ version }}.tar.gz
  sha256: 904e19093dd6578a5ce01a8274e3e228d556d47be3bda328da2d3601c5240c4f

build:
  entry_points:
    - ulid = ulid.__main__:entrypoint
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=3.9

test:
  imports:
    - ulid
  commands:
    - pip check
    - ulid --help
  requires:
    - pip

about:
  summary: Universally unique lexicographically sortable identifier
  home: https://github.com/mdomke/python-ulid
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
